### ISSUE TITLE
xcode 11 issue

### ISSUE THREAD

**Issue by eramrit78** [BaseflowIT/XamarinMediaManager#625]
## 🐛 Bug Report

IOS app crash after upgrade to xcode 11 on ios 10.3

### Expected behavior
It should be work

### Configuration

**Version:** 1.x

**Platform:** 
- [x] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [ ] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [ ] :monkey: Xamarin.Forms

**Comment by martijn00** [comment]
It works fine for me. Please provide more details, like a stacktrace, and in depth info
